### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by GeorgeRNG**
I had to cut the skin preview when hovering a head and another mixin by samman in chat related to color something.

### CODE REVIEW

**Comment by homchom** [comment]
can you elaborate? did you remove features and/or code in this pr?

**Comment by SamMan56** [comment]
fyi the coloured chat box is for this old df++ feature that coloured the chat box support blue when using the send to support chat keybind
image

**Comment by GeorgeRNG** [comment]
I commented out code I couldn't work out how to fix
- The skin preview, I couldn't find a good place in the class to inject into. https://github.com/homchom/recode/pull/55/files#diff-0455aabfcff53f2dfc179206d040d63f34a2f4bde3927b5a736bb1f37904e16a
- SamMan seemed to have posted the other thing I cut. https://github.com/homchom/recode/pull/55/files#diff-8158687927ec7d9df3fbc162854818129d01832f4055dada7170c77c66e9abb3

**Comment by homchom** [comment]
alright thanks, i'll work on these now.

**Review by HellishBro — COMMENTED** [review]
yes

**Review by homchom — CHANGES_REQUESTED** [review]
awaiting changes as discussed in the discord contributors channel

**Comment by GeorgeRNG** [comment]
Completed the changes.
And I'm pretty sure there's a way to close requested changes but I can't find it

**Review by homchom — APPROVED** [review]

**Pull request merged**
