### PR TITLE
refactor: remove janky bloat

### PR DESCRIPTION
**Pull request by tk2217**

### CODE REVIEW

**Comment by homchom** [comment]
A few questions/comments:

1. I think we should keep message stacking; it's very useful for when players are spamming.
2. I think we should also keep highlighting for now, but maybe later we can look into streamlining it.
3. Does removing the ws-server break any current features? Is anything using it?

**Comment by tk2217** [comment]
Ws server breaks a few things but all of those can be done with http and without auth.

**Comment by homchom** [comment]
In that case, I should probably start doing the Kotlin migration now, since I don't think it's worth recoding all of the features to use HTTP, and then doing it again when I use ktor (which uses coroutines, and therefore will probably look pretty different than any Java alternative).

Can you give me a list of all features that need to be fixed? Or is there a way I can do a code search in IntelliJ to find them?

**Comment by tk2217** [comment]
Most things use either http or websocket. For http, most things are through `Recode.HTTP_CLIENT` and `WebUtil`. With websockets, anything pertaining to that cna be found by searching for `websocket`.

**Comment by homchom** [comment]
I didn't realize the mod already had HTTP requests implemented. In that case, there is no need to use ktor yet. Thanks for moving everything over!

**Comment by homchom** [comment]
Will commenting this here reopen this?

**Pull request merged**
